import { FileText } from "lucide-react";
import { toFlat } from "./utils";
import type { SectionDef, StagePreparation } from "./section-types";

export const persiapanSection: SectionDef<StagePreparation, "persiapan"> = {
  id: "persiapan",
  label: "Tahap Persiapan",
  icon: FileText,
  columns: ["ID", "No Agenda", "Tanggal DPP", "Paket", "Pagu Aktif", "Status"],
  pick: (x) => x.paket_pbj_nama,
  toRow: (x) => [
    String(x.id),
    x.agenda_no,
    x.dpp_tgl,
    x.paket_pbj_nama,
    new Intl.NumberFormat("id-ID").format(x.anggaran_pagu_aktif),
    x.keterangan_tambahan,
  ],
  filters: [
    {
      name: "keterangan_tambahan",
      label: "Status",
      select: [
        { value: "Kaji Ulang PPK", label: "Kaji Ulang PPK" },
        { value: "Sedang Berproses", label: "Sedang Berproses" },
        { value: "Selesai Dilaporkan", label: "Selesai Dilaporkan" },
      ],
    },
    { name: "dpp_tgl", label: "Tanggal DPP", type: "date" },
    { name: "agenda_no", label: "No Agenda" },
    { name: "ulp_ppk_code_id", label: "PPK (ID)", type: "number" },
    { name: "ulp_mak_code_id", label: "MAK (ID)", type: "number" },
    { name: "ulp_satker_unit_pengendali_id", label: "Satker Pengendali (ID)", type: "number" },
  ],
  fields: [
    { name: "id", label: "ID", type: "number", readonly: true },
    { name: "dpp_diterima_tgl", label: "Tanggal Diterima DPP", type: "date" },
    { name: "agenda_no", label: "No Agenda" },
    { name: "ulp_satker_unit_pengendali_id", label: "Satker Pengendali (ID)", type: "number" },
    { name: "ulp_satker_unit_enduser_id", label: "Satker End User (ID)", type: "number" },
    { name: "surat_enduser_no", label: "No Surat End User" },
    { name: "surat_enduser_tgl", label: "Tanggal Surat End User", type: "date" },
    { name: "surat_enduser_hal", label: "Hal Surat End User", textarea: true },
    { name: "ulp_ppk_code_id", label: "PPK (ID)", type: "number" },
    { name: "surat_ppk_no", label: "No Surat PPK" },
    { name: "dpp_tgl", label: "Tanggal DPP", type: "date" },
    { name: "surat_ppk_hal", label: "Hal Surat PPK", textarea: true },
    { name: "paket_pbj_nama", label: "Nama Paket PBJ", textarea: true },
    { name: "anggaran_pagu_nonaktif", label: "Pagu Non Aktif", type: "number" },
    { name: "anggaran_pagu_aktif", label: "Pagu Aktif", type: "number" },
    { name: "ulp_mak_code_id", label: "MAK (ID)", type: "number" },
    { name: "kelompok_belanja_modal", label: "Kelompok Belanja Modal", type: "number" },
    { name: "kelompok_belanja_operasional", label: "Kelompok Belanja Operasional", type: "number" },
    {
      name: "keterangan_tambahan",
      label: "Status",
      select: [
        { value: "Kaji Ulang PPK", label: "Kaji Ulang PPK" },
        { value: "Sedang Berproses", label: "Sedang Berproses" },
        { value: "Selesai Dilaporkan", label: "Selesai Dilaporkan" },
      ],
    },
    { name: "created_at", label: "Created At", readonly: true },
    { name: "updated_at", label: "Updated At", readonly: true },
    { name: "deleted_at", label: "Deleted At", readonly: true },
  ],
  initial: (item) => toFlat(item),
  build: ({ formData, prev, items }) => ({
    id: prev?.id ?? Math.max(0, ...items.map((m) => m.id)) + 1,
    dpp_diterima_tgl: formData.dpp_diterima_tgl || "",
    agenda_no: formData.agenda_no || "",
    ulp_satker_unit_pengendali_id: Number(formData.ulp_satker_unit_pengendali_id || 0),
    ulp_satker_unit_enduser_id: Number(formData.ulp_satker_unit_enduser_id || 0),
    surat_enduser_no: formData.surat_enduser_no || "",
    surat_enduser_tgl: formData.surat_enduser_tgl || "",
    surat_enduser_hal: formData.surat_enduser_hal || "",
    ulp_ppk_code_id: Number(formData.ulp_ppk_code_id || 0),
    surat_ppk_no: formData.surat_ppk_no || "",
    dpp_tgl: formData.dpp_tgl || "",
    surat_ppk_hal: formData.surat_ppk_hal || "",
    paket_pbj_nama: formData.paket_pbj_nama || "",
    anggaran_pagu_nonaktif: Number(formData.anggaran_pagu_nonaktif || 0),
    anggaran_pagu_aktif: Number(formData.anggaran_pagu_aktif || 0),
    ulp_mak_code_id: Number(formData.ulp_mak_code_id || 0),
    kelompok_belanja_modal: Number(formData.kelompok_belanja_modal || 0),
    kelompok_belanja_operasional: Number(formData.kelompok_belanja_operasional || 0),
    keterangan_tambahan:
      (formData.keterangan_tambahan as StagePreparation["keterangan_tambahan"]) ||
      "Sedang Berproses",
    created_at: prev?.created_at ?? new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  }),
};
