import { Database } from "lucide-react";
import { toFlat } from "./utils";
import type { SectionDef, StageProcess } from "./section-types";

export const prosesSection: SectionDef<StageProcess, "proses"> = {
  id: "proses",
  label: "Proses Pemilihan",
  icon: Database,
  columns: ["ID", "RUP", "Metode", "Kriteria", "Realisasi"],
  pick: (x) => x.metode_pemilihan,
  toRow: (x) => [
    String(x.id),
    x.rup_kode,
    x.metode_pemilihan,
    x.kriteria_barangjasa,
    new Intl.NumberFormat("id-ID").format(x.nilai_realisasi || 0),
  ],
  filters: [
    {
      name: "metode_pemilihan",
      label: "Metode",
      select: [
        { value: "Pengadaan Langsung", label: "Pengadaan Langsung" },
        { value: "Penunjukan Langsung", label: "Penunjukan Langsung" },
        { value: "Tender", label: "Tender" },
        { value: "E-Pengadaan Langsung", label: "E-Pengadaan Langsung" },
        { value: "E-Penunjukan Langsung", label: "E-Penunjukan Langsung" },
        { value: "E-Purchasing", label: "E-Purchasing" },
        { value: "E-Tender", label: "E-Tender" },
      ],
    },
    {
      name: "kriteria_barangjasa",
      label: "Kriteria",
      select: [
        { value: "Barang", label: "Barang" },
        { value: "Jasa Lainnya", label: "Jasa Lainnya" },
        { value: "Pekerjaan Konstruksi", label: "Pekerjaan Konstruksi" },
      ],
    },
    {
      name: "is_rup",
      label: "RUP",
      select: [
        { value: "true", label: "Ya" },
        { value: "false", label: "Tidak" },
      ],
    },
    {
      name: "is_eproc",
      label: "E-Proc",
      select: [
        { value: "true", label: "Ya" },
        { value: "false", label: "Tidak" },
      ],
    },
    {
      name: "is_manual",
      label: "Manual",
      select: [
        { value: "true", label: "Ya" },
        { value: "false", label: "Tidak" },
      ],
    },
    { name: "rup_kode", label: "Kode RUP" },
    { name: "nilai_realisasi", label: "Nilai Realisasi", type: "number" },
    { name: "ulp_stage_preparation_id", label: "Tahap Persiapan (ID)", type: "number" },
    { name: "ulp_perusahaan_id", label: "Perusahaan (ID)", type: "number" },
  ],
  fields: [
    { name: "id", label: "ID", type: "number", readonly: true },
    { name: "ulp_stage_preparation_id", label: "Tahap Persiapan (ID)", type: "number" },
    { name: "rup_kode", label: "Kode RUP" },
    {
      name: "metode_pemilihan",
      label: "Metode",
      select: [
        { value: "Pengadaan Langsung", label: "Pengadaan Langsung" },
        { value: "Penunjukan Langsung", label: "Penunjukan Langsung" },
        { value: "Tender", label: "Tender" },
        { value: "E-Pengadaan Langsung", label: "E-Pengadaan Langsung" },
        { value: "E-Penunjukan Langsung", label: "E-Penunjukan Langsung" },
        { value: "E-Purchasing", label: "E-Purchasing" },
        { value: "E-Tender", label: "E-Tender" },
      ],
    },
    {
      name: "kriteria_barangjasa",
      label: "Kriteria",
      select: [
        { value: "Barang", label: "Barang" },
        { value: "Jasa Lainnya", label: "Jasa Lainnya" },
        { value: "Pekerjaan Konstruksi", label: "Pekerjaan Konstruksi" },
      ],
    },
    { name: "nilai_realisasi", label: "Nilai Realisasi", type: "number" },
    {
      name: "is_rup",
      label: "RUP",
      select: [
        { value: "true", label: "Ya" },
        { value: "false", label: "Tidak" },
      ],
    },
    {
      name: "is_eproc",
      label: "E-Proc",
      select: [
        { value: "true", label: "Ya" },
        { value: "false", label: "Tidak" },
      ],
    },
    {
      name: "is_manual",
      label: "Manual",
      select: [
        { value: "true", label: "Ya" },
        { value: "false", label: "Tidak" },
      ],
    },
    { name: "lembar_catatan_pengecekan_hps_tgl", label: "Lembar Catatan Pengecekan HPS (Tgl)", type: "date" },
    { name: "lembar_catatan_pengecekan_hps_pic", label: "Lembar Catatan Pengecekan HPS (PIC)" },
    { name: "koreksi_aritmatika_tgl", label: "Koreksi Aritmatika (Tgl)", type: "date" },
    { name: "koreksi_aritmatika_pic", label: "Koreksi Aritmatika (PIC)" },
    { name: "lembar_persiapan_tgl", label: "Lembar Persiapan (Tgl)", type: "date" },
    { name: "lembar_persiapan_pic_buat", label: "Lembar Persiapan (PIC Buat)" },
    { name: "lembar_persiapan_pic_pokja", label: "Lembar Persiapan (PIC Ka. Pokja)" },
    { name: "pengumuman_pemilihan_lpse_no", label: "Pengumuman Pemilihan LPSE (No)" },
    { name: "pengumuman_pemilihan_lpse_tgl", label: "Pengumuman Pemilihan LPSE (Tgl)", type: "date" },
    { name: "pengumuman_pemilihan_lpse_pic", label: "Pengumuman Pemilihan LPSE (PIC)" },
    { name: "dokumen_pemilihan_spph_no", label: "Dokumen Pemilihan SPPH (No)" },
    { name: "dokumen_pemilihan_spph_tgl", label: "Dokumen Pemilihan SPPH (Tgl)", type: "date" },
    { name: "dokumen_pemilihan_spph_pic", label: "Dokumen Pemilihan SPPH (PIC)" },
    { name: "registrasi_draft_paket_pbj_spse_tgl", label: "Registrasi Draft Paket PBJ SPSE (Tgl)", type: "date" },
    { name: "registrasi_draft_paket_pbj_spse_pic", label: "Registrasi Draft Paket PBJ SPSE (PIC)" },
    { name: "undangan_reviu_dpp_no", label: "Undangan Reviu DPP (No)" },
    { name: "undangan_reviu_dpp_tgl", label: "Undangan Reviu DPP (Tgl)", type: "date" },
    { name: "undangan_reviu_dpp_pic", label: "Undangan Reviu DPP (PIC)" },
    { name: "lembar_daftar_hadir_reviu_dpp_tgl", label: "Daftar Hadir Reviu DPP (Tgl)", type: "date" },
    { name: "lembar_daftar_hadir_reviu_dpp_pic", label: "Daftar Hadir Reviu DPP (PIC)" },
    { name: "ba_reviu_dpp_no", label: "BA Reviu DPP (No)" },
    { name: "ba_reviu_dpp_tgl", label: "BA Reviu DPP (Tgl)", type: "date" },
    { name: "ba_reviu_dpp_pic", label: "BA Reviu DPP (PIC)" },
    { name: "undangan_pemberian_penjelasan_no", label: "Undangan Pemberian Penjelasan (No)" },
    { name: "undangan_pemberian_penjelasan_tgl", label: "Undangan Pemberian Penjelasan (Tgl)", type: "date" },
    { name: "undangan_pemberian_penjelasan_pic", label: "Undangan Pemberian Penjelasan (PIC)" },
    { name: "lembar_daftar_hadir_pemberian_penjelasan_tgl", label: "Daftar Hadir Pemberian Penjelasan (Tgl)", type: "date" },
    { name: "lembar_daftar_hadir_pemberian_penjelasan_pic", label: "Daftar Hadir Pemberian Penjelasan (PIC)" },
    { name: "ba_pemberian_penjelasan_no", label: "BA Pemberian Penjelasan (No)" },
    { name: "ba_pemberian_penjelasan_tgl", label: "BA Pemberian Penjelasan (Tgl)", type: "date" },
    { name: "ba_pemberian_penjelasan_pic", label: "BA Pemberian Penjelasan (PIC)" },
    { name: "dekripsi_data_penawaran_tgl", label: "Dekripsi Data Penawaran (Tgl)", type: "date" },
    { name: "dekripsi_data_penawaran_pic", label: "Dekripsi Data Penawaran (PIC)" },
    { name: "ba_pembukaan_dokumen_penawaran_no", label: "BA Pembukaan Dokumen Penawaran (No)" },
    { name: "ba_pembukaan_dokumen_penawaran_tgl", label: "BA Pembukaan Dokumen Penawaran (Tgl)", type: "date" },
    { name: "ba_pembukaan_dokumen_penawaran_pic", label: "BA Pembukaan Dokumen Penawaran (PIC)" },
    { name: "lembar_koreksi_aritmatika_penawaran_harga_tgl", label: "Koreksi Aritmatika Penawaran Harga (Tgl)", type: "date" },
    { name: "lembar_koreksi_aritmatika_penawaran_harga_pic", label: "Koreksi Aritmatika Penawaran Harga (PIC)" },
    { name: "kertas_kerja_evaluasi_penawaran_tgl", label: "Kertas Kerja Evaluasi Penawaran (Tgl)", type: "date" },
    { name: "kertas_kerja_evaluasi_penawaran_pic", label: "Kertas Kerja Evaluasi Penawaran (PIC)" },
    { name: "ba_evaluasi_penawaran_no", label: "BA Evaluasi Penawaran (No)" },
    { name: "ba_evaluasi_penawaran_tgl", label: "BA Evaluasi Penawaran (Tgl)", type: "date" },
    { name: "ba_evaluasi_penawaran_pic", label: "BA Evaluasi Penawaran (PIC)" },
    { name: "undangan_verifikasi_pembuktian_kualifikasi_no", label: "Undangan Verifikasi Kualifikasi (No)" },
    { name: "undangan_verifikasi_pembuktian_kualifikasi_tgl", label: "Undangan Verifikasi Kualifikasi (Tgl)", type: "date" },
    { name: "undangan_verifikasi_pembuktian_kualifikasi_pic", label: "Undangan Verifikasi Kualifikasi (PIC)" },
    { name: "lembar_daftar_hadir_verifikasi_pembuktian_kualifikasi_tgl", label: "Daftar Hadir Verifikasi Kualifikasi (Tgl)", type: "date" },
    { name: "lembar_daftar_hadir_verifikasi_pembuktian_kualifikasi_pic", label: "Daftar Hadir Verifikasi Kualifikasi (PIC)" },
    { name: "lembar_nego_teknis_harga_tgl", label: "Lembar Nego Teknis dan Harga (Tgl)", type: "date" },
    { name: "lembar_nego_teknis_harga_pic", label: "Lembar Nego Teknis dan Harga (PIC)" },
    { name: "ba_klarifikasi_negosiasi_harga_no", label: "BA Klarifikasi & Negosiasi Harga (No)" },
    { name: "ba_klarifikasi_negosiasi_harga_tgl", label: "BA Klarifikasi & Negosiasi Harga (Tgl)", type: "date" },
    { name: "ba_klarifikasi_negosiasi_harga_pic", label: "BA Klarifikasi & Negosiasi Harga (PIC)" },
    { name: "ba_hasil_pemilihan_no", label: "BA Hasil Pemilihan (No)" },
    { name: "ba_hasil_pemilihan_tgl", label: "BA Hasil Pemilihan (Tgl)", type: "date" },
    { name: "ba_hasil_pemilihan_pic", label: "BA Hasil Pemilihan (PIC)" },
    { name: "penetapan_pemenang_pemilihan_no", label: "Penetapan Pemenang (No)" },
    { name: "penetapan_pemenang_pemilihan_tgl", label: "Penetapan Pemenang (Tgl)", type: "date" },
    { name: "penetapan_pemenang_pemilihan_pic", label: "Penetapan Pemenang (PIC)" },
    { name: "pengumuman_pemenang_pemilihan_no", label: "Pengumuman Pemenang (No)" },
    { name: "pengumuman_pemenang_pemilihan_tgl", label: "Pengumuman Pemenang (Tgl)", type: "date" },
    { name: "pengumuman_pemenang_pemilihan_pic", label: "Pengumuman Pemenang (PIC)" },
    { name: "sanggahan_no", label: "Sanggahan (No)" },
    { name: "sanggahan_tgl", label: "Sanggahan (Tgl)", type: "date" },
    { name: "sanggahan_nama_peserta", label: "Sanggahan (Nama Peserta)" },
    { name: "jawaban_sanggah_no", label: "Jawaban Sanggah (No)" },
    { name: "jawaban_sanggah_tgl", label: "Jawaban Sanggah (Tgl)", type: "date" },
    { name: "jawaban_sanggah_pic", label: "Jawaban Sanggah (PIC)" },
    { name: "surat_usulan_kaji_ulang_paket_no", label: "Surat Usulan Kaji Ulang Paket (No)" },
    { name: "surat_usulan_kaji_ulang_paket_tgl", label: "Surat Usulan Kaji Ulang Paket (Tgl)", type: "date" },
    { name: "surat_usulan_kaji_ulang_paket_pic", label: "Surat Usulan Kaji Ulang Paket (PIC)" },
    { name: "laporan_hasil_pemilihan_no", label: "Laporan Hasil Pemilihan (No)" },
    { name: "laporan_hasil_pemilihan_tgl", label: "Laporan Hasil Pemilihan (Tgl)", type: "date" },
    { name: "laporan_hasil_pemilihan_pic", label: "Laporan Hasil Pemilihan (PIC)" },
    { name: "dokumen_spb_spk_kontrak_pic", label: "Dokumen SPB/SPK/Kontrak (PIC)" },
    { name: "dokumen_spb_spk_kontrak_no", label: "Dokumen SPB/SPK/Kontrak (Nomor)" },
    { name: "dokumen_spb_spk_kontrak_tgl", label: "Dokumen SPB/SPK/Kontrak (Tanggal)", type: "date" },
    { name: "nilai_kontrak_blu", label: "Nilai Kontrak (BLU)", type: "number" },
    { name: "nilai_kontrak_non_blu", label: "Nilai Kontrak (Non BLU)", type: "number" },
    { name: "jangka_waktu_pekerjaan", label: "Jangka Waktu Pekerjaan", type: "number" },
    { name: "jangka_waktu_pekerjaan_satuan", label: "Satuan Jangka Waktu" },
    { name: "ulp_perusahaan_id", label: "Perusahaan (ID)", type: "number" },
    { name: "created_at", label: "Created At", readonly: true },
    { name: "updated_at", label: "Updated At", readonly: true },
    { name: "deleted_at", label: "Deleted At", readonly: true },
  ],
  initial: (item) => toFlat(item),
  build: ({ formData, prev, items }) => ({
    id: prev?.id ?? Math.max(0, ...items.map((m) => m.id)) + 1,
    ulp_stage_preparation_id: Number(formData.ulp_stage_preparation_id || 0),
    is_rup: formData.is_rup === "true",
    is_eproc: formData.is_eproc === "true",
    is_manual: formData.is_manual === "true",
    rup_kode: formData.rup_kode || "",
    metode_pemilihan:
      (formData.metode_pemilihan as StageProcess["metode_pemilihan"]) ||
      "Pengadaan Langsung",
    kriteria_barangjasa:
      (formData.kriteria_barangjasa as StageProcess["kriteria_barangjasa"]) || "Barang",
    lembar_catatan_pengecekan_hps_tgl: formData.lembar_catatan_pengecekan_hps_tgl || "",
    lembar_catatan_pengecekan_hps_pic: formData.lembar_catatan_pengecekan_hps_pic || "",
    koreksi_aritmatika_tgl: formData.koreksi_aritmatika_tgl || "",
    koreksi_aritmatika_pic: formData.koreksi_aritmatika_pic || "",
    lembar_persiapan_tgl: formData.lembar_persiapan_tgl || "",
    lembar_persiapan_pic_buat: formData.lembar_persiapan_pic_buat || "",
    lembar_persiapan_pic_pokja: formData.lembar_persiapan_pic_pokja || "",
    pengumuman_pemilihan_lpse_no: formData.pengumuman_pemilihan_lpse_no || "",
    pengumuman_pemilihan_lpse_tgl: formData.pengumuman_pemilihan_lpse_tgl || "",
    pengumuman_pemilihan_lpse_pic: formData.pengumuman_pemilihan_lpse_pic || "",
    dokumen_pemilihan_spph_no: formData.dokumen_pemilihan_spph_no || "",
    dokumen_pemilihan_spph_tgl: formData.dokumen_pemilihan_spph_tgl || "",
    dokumen_pemilihan_spph_pic: formData.dokumen_pemilihan_spph_pic || "",
    registrasi_draft_paket_pbj_spse_tgl: formData.registrasi_draft_paket_pbj_spse_tgl || "",
    registrasi_draft_paket_pbj_spse_pic: formData.registrasi_draft_paket_pbj_spse_pic || "",
    undangan_reviu_dpp_no: formData.undangan_reviu_dpp_no || "",
    undangan_reviu_dpp_tgl: formData.undangan_reviu_dpp_tgl || "",
    undangan_reviu_dpp_pic: formData.undangan_reviu_dpp_pic || "",
    lembar_daftar_hadir_reviu_dpp_tgl: formData.lembar_daftar_hadir_reviu_dpp_tgl || "",
    lembar_daftar_hadir_reviu_dpp_pic: formData.lembar_daftar_hadir_reviu_dpp_pic || "",
    ba_reviu_dpp_no: formData.ba_reviu_dpp_no || "",
    ba_reviu_dpp_tgl: formData.ba_reviu_dpp_tgl || "",
    ba_reviu_dpp_pic: formData.ba_reviu_dpp_pic || "",
    undangan_pemberian_penjelasan_no: formData.undangan_pemberian_penjelasan_no || "",
    undangan_pemberian_penjelasan_tgl: formData.undangan_pemberian_penjelasan_tgl || "",
    undangan_pemberian_penjelasan_pic: formData.undangan_pemberian_penjelasan_pic || "",
    lembar_daftar_hadir_pemberian_penjelasan_tgl:
      formData.lembar_daftar_hadir_pemberian_penjelasan_tgl || "",
    lembar_daftar_hadir_pemberian_penjelasan_pic:
      formData.lembar_daftar_hadir_pemberian_penjelasan_pic || "",
    ba_pemberian_penjelasan_no: formData.ba_pemberian_penjelasan_no || "",
    ba_pemberian_penjelasan_tgl: formData.ba_pemberian_penjelasan_tgl || "",
    ba_pemberian_penjelasan_pic: formData.ba_pemberian_penjelasan_pic || "",
    dekripsi_data_penawaran_tgl: formData.dekripsi_data_penawaran_tgl || "",
    dekripsi_data_penawaran_pic: formData.dekripsi_data_penawaran_pic || "",
    ba_pembukaan_dokumen_penawaran_no: formData.ba_pembukaan_dokumen_penawaran_no || "",
    ba_pembukaan_dokumen_penawaran_tgl: formData.ba_pembukaan_dokumen_penawaran_tgl || "",
    ba_pembukaan_dokumen_penawaran_pic: formData.ba_pembukaan_dokumen_penawaran_pic || "",
    lembar_koreksi_aritmatika_penawaran_harga_tgl:
      formData.lembar_koreksi_aritmatika_penawaran_harga_tgl || "",
    lembar_koreksi_aritmatika_penawaran_harga_pic:
      formData.lembar_koreksi_aritmatika_penawaran_harga_pic || "",
    kertas_kerja_evaluasi_penawaran_tgl: formData.kertas_kerja_evaluasi_penawaran_tgl || "",
    kertas_kerja_evaluasi_penawaran_pic: formData.kertas_kerja_evaluasi_penawaran_pic || "",
    ba_evaluasi_penawaran_no: formData.ba_evaluasi_penawaran_no || "",
    ba_evaluasi_penawaran_tgl: formData.ba_evaluasi_penawaran_tgl || "",
    ba_evaluasi_penawaran_pic: formData.ba_evaluasi_penawaran_pic || "",
    undangan_verifikasi_pembuktian_kualifikasi_no:
      formData.undangan_verifikasi_pembuktian_kualifikasi_no || "",
    undangan_verifikasi_pembuktian_kualifikasi_tgl:
      formData.undangan_verifikasi_pembuktian_kualifikasi_tgl || "",
    undangan_verifikasi_pembuktian_kualifikasi_pic:
      formData.undangan_verifikasi_pembuktian_kualifikasi_pic || "",
    lembar_daftar_hadir_verifikasi_pembuktian_kualifikasi_tgl:
      formData.lembar_daftar_hadir_verifikasi_pembuktian_kualifikasi_tgl || "",
    lembar_daftar_hadir_verifikasi_pembuktian_kualifikasi_pic:
      formData.lembar_daftar_hadir_verifikasi_pembuktian_kualifikasi_pic || "",
    lembar_nego_teknis_harga_tgl: formData.lembar_nego_teknis_harga_tgl || "",
    lembar_nego_teknis_harga_pic: formData.lembar_nego_teknis_harga_pic || "",
    ba_klarifikasi_negosiasi_harga_no: formData.ba_klarifikasi_negosiasi_harga_no || "",
    ba_klarifikasi_negosiasi_harga_tgl: formData.ba_klarifikasi_negosiasi_harga_tgl || "",
    ba_klarifikasi_negosiasi_harga_pic: formData.ba_klarifikasi_negosiasi_harga_pic || "",
    ba_hasil_pemilihan_no: formData.ba_hasil_pemilihan_no || "",
    ba_hasil_pemilihan_tgl: formData.ba_hasil_pemilihan_tgl || "",
    ba_hasil_pemilihan_pic: formData.ba_hasil_pemilihan_pic || "",
    penetapan_pemenang_pemilihan_no: formData.penetapan_pemenang_pemilihan_no || "",
    penetapan_pemenang_pemilihan_tgl: formData.penetapan_pemenang_pemilihan_tgl || "",
    penetapan_pemenang_pemilihan_pic: formData.penetapan_pemenang_pemilihan_pic || "",
    pengumuman_pemenang_pemilihan_no: formData.pengumuman_pemenang_pemilihan_no || "",
    pengumuman_pemenang_pemilihan_tgl: formData.pengumuman_pemenang_pemilihan_tgl || "",
    pengumuman_pemenang_pemilihan_pic: formData.pengumuman_pemenang_pemilihan_pic || "",
    sanggahan_no: formData.sanggahan_no || "",
    sanggahan_tgl: formData.sanggahan_tgl || "",
    sanggahan_nama_peserta: formData.sanggahan_nama_peserta || "",
    jawaban_sanggah_no: formData.jawaban_sanggah_no || "",
    jawaban_sanggah_tgl: formData.jawaban_sanggah_tgl || "",
    jawaban_sanggah_pic: formData.jawaban_sanggah_pic || "",
    surat_usulan_kaji_ulang_paket_no: formData.surat_usulan_kaji_ulang_paket_no || "",
    surat_usulan_kaji_ulang_paket_tgl: formData.surat_usulan_kaji_ulang_paket_tgl || "",
    surat_usulan_kaji_ulang_paket_pic: formData.surat_usulan_kaji_ulang_paket_pic || "",
    laporan_hasil_pemilihan_no: formData.laporan_hasil_pemilihan_no || "",
    laporan_hasil_pemilihan_tgl: formData.laporan_hasil_pemilihan_tgl || "",
    laporan_hasil_pemilihan_pic: formData.laporan_hasil_pemilihan_pic || "",
    nilai_realisasi: Number(formData.nilai_realisasi || 0),
    dokumen_spb_spk_kontrak_pic: formData.dokumen_spb_spk_kontrak_pic || "",
    dokumen_spb_spk_kontrak_no: formData.dokumen_spb_spk_kontrak_no || "",
    dokumen_spb_spk_kontrak_tgl: formData.dokumen_spb_spk_kontrak_tgl || "",
    nilai_kontrak_blu: Number(formData.nilai_kontrak_blu || 0),
    nilai_kontrak_non_blu: Number(formData.nilai_kontrak_non_blu || 0),
    jangka_waktu_pekerjaan: Number(formData.jangka_waktu_pekerjaan || 0),
    jangka_waktu_pekerjaan_satuan: formData.jangka_waktu_pekerjaan_satuan || "",
    ulp_perusahaan_id: Number(formData.ulp_perusahaan_id || 0),
    created_at: prev?.created_at ?? new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted_at: null,
  }),
};
